f=open("data.txt")

print("error:",e)

print("file handling attempted")
